-- Tabella per gli alloggi del modulo SICAR
CREATE TABLE `aa_sicar_data` (
    `id` INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    `immobile` VARCHAR(64) NOT NULL,
    `descrizione` VARCHAR(255) NOT NULL,
    `tipologia_utilizzo` VARCHAR(64) NOT NULL,
    `stato_conservazione` VARCHAR(64) NOT NULL,
    `anno_ristrutturazione` INT DEFAULT NULL,
    `condominio_misto` BOOLEAN NOT NULL DEFAULT 0,
    `superficie_netta` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `superficie_utile_abitabile` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `piano` INT NOT NULL DEFAULT 0,
    `ascensore` BOOLEAN NOT NULL DEFAULT 0,
    `fruibile_dis` BOOLEAN NOT NULL DEFAULT 0,
    `gestione` JSON NOT NULL,
    `proprieta` JSON NOT NULL,
    `stato` JSON NOT NULL,
    `note` TEXT DEFAULT NULL,
    KEY `idx_immobile` (`immobile`),
    KEY `idx_tipologia_utilizzo` (`tipologia_utilizzo`),
    KEY `idx_stato_conservazione` (`stato_conservazione`),
    KEY `idx_condominio_misto` (`condominio_misto`),
    KEY `idx_piano` (`piano`),
    KEY `idx_ascensore` (`ascensore`),
    KEY `idx_fruibile_dis` (`fruibile_dis`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alloggi associati agli immobili';
